package mod.upcraftlp.hardcoresurvival;

import com.mojang.realmsclient.gui.ChatFormatting;

import mod.upcraftlp.hardcoresurvival.proxy.CommonProxy;
import mod.upcraftlp.hardcoresurvival.util.SysUtils;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;

@Mod(name = Reference.NAME, version = Reference.VERSION, modid = Reference.MOD_ID)
public class Main {
	
	@Instance(Reference.MOD_ID)
	private Main instance;
	
	@SidedProxy(clientSide = Reference.CLIENT_PATH, serverSide = Reference.SERVER_PATH)
	public static CommonProxy proxy;
	
	public Main getInstance()
	{
		return this.instance;
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		if(event.getSide() == Side.CLIENT)
		{
			ModMetadata data = event.getModMetadata();
			data.autogenerated = false;
			data.url = Reference.MOD_URL;
			data.name = ChatFormatting.AQUA + Reference.NAME;
			data.credits = "UpcraftLP";
			data.authorList.add("UpcraftLP");
			data.modId = Reference.MOD_ID;
			data.version = Reference.VERSION;
			data.description = Reference.NAME + " " + Reference.MCVERSION + " by " + data.credits;
			//TODO (maybe)
			//data.logoFile = "assets/" + Reference.MOD_ID + "/textures/gui/logo.png";
		}
		
		proxy.preInit(event);
		SysUtils.println("Pre-Initialization finished.");
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		proxy.init(event);
		SysUtils.println("Initialization finished.");
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		proxy.postInit(event);
		SysUtils.println("Post-Initialization finished.");
	}
	
}
